name: Build & Release Tropicraft

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Services (Release)
      uses: Kir-Antipov/mc-publish@v3.1
      if: "!github.event.release.prerelease"
      with:
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-type: release

    - name: Publish to Services (Beta)
      uses: Kir-Antipov/mc-publish@v3.1
      if: "!github.event.release.prerelease"
      with:
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-type: beta