name: Build & Release Tropicraft

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Environment Variables
      run: echo "##[set-output name=mcversion;]$(grep 'minecraft_version' gradle.properties | cut -f2- -d=)"

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Services (Release)
      uses: Kir-Antipov/mc-publish@v3.1
      if: "!github.event.release.prerelease"
      with:
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-type: release
        game-versions: |
          ${{ steps.init.outputs.mcversion }}

    - name: Publish to Services (Beta)
      uses: Kir-Antipov/mc-publish@v3.1
      if: "!github.event.release.prerelease"
      with:
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-type: beta
        game-versions: |
          ${{ steps.init.outputs.mcversion }}